todo_manager/todo_list/urls.py
from django.urls import path

from todo_list.views import (
    ToDoListIndexView,
    ToDoListView,
    ToDoListDoneView,
    ToDoDetailView,
    ToDoItemCreateView,
    ToDoItemUpdateView,
    ToDoItemDeleteView,
)

app_name = "todo_list"
urlpatterns = [
    path("", ToDoListView.as_view(), name="index"),
    path("list/", ToDoListIndexView.as_view(), name="list"),
    path("done/", ToDoListDoneView.as_view(), name="done"),
    path("<int:pk>/", ToDoDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", ToDoItemUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", ToDoItemDeleteView.as_view(), name="delete"),
    path("create/", ToDoItemCreateView.as_view(), name="create"),
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="index.html"),
        name="index",
    ),
    path("todos/", include("todo_list.urls")),
    path("admin/", admin.site.urls),
]

todo_manager/todo_list/models.py
from django.db import models
from django.urls import reverse


class ToDoItem(models.Model):
    class Meta:
        ordering = ("-id",)
        verbose_name = "ToDo Item"

    title = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=False)
    done = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse(
            "todo_list:detail",
            kwargs={"pk": self.pk},
        )

    def __str__(self) -> str:
        return self.title

todo_manager/todo_list/forms.py
from django import forms
from django.forms import Textarea

from todo_list.models import ToDoItem


class ToDoItemCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = (
            "title",
            "description",
        )
        widgets = {
            "description": Textarea(attrs={"cols": 30, "rows": 5}),
        }
        labels = {
            "title": "Task title",
        }


class ToDoItemUpdateForm(forms.ModelForm):
    class Meta(ToDoItemCreateForm.Meta):
        fields = (
            "title",
            "description",
            "done",
        )

todo_manager/todo_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from todo_list.forms import ToDoItemCreateForm, ToDoItemUpdateForm
from todo_list.models import ToDoItem


class ToDoListView(ListView):
    template_name = "todo_list/index.html"
    model = ToDoItem
    context_object_name = "todo_items"

    # TODO: custom qs, archived
    def get_queryset(self):
        return super().get_queryset()[:3]


class ToDoListIndexView(TemplateView):
    template_name = "todo_list/todoitem_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        todo_items = ToDoItem.objects.filter(archived=False)
        context["todo_items"] = todo_items
        return context


class ToDoListDoneView(ListView):
    template_name = "todo_list/done_items.html"
    model = ToDoItem
    context_object_name = "todo_items"

    def get_queryset(self):
        return super().get_queryset().filter(done=True, archived=False)


class ToDoDetailView(DetailView):
    template_name = "todo_list/todoitem_detail.html"
    queryset = ToDoItem.objects.filter(archived=False)
    context_object_name = "todo_item"


class ToDoItemCreateView(CreateView):
    model = ToDoItem
    form_class = ToDoItemCreateForm


class ToDoItemUpdateView(UpdateView):
    model = ToDoItem
    form_class = ToDoItemUpdateForm
    template_name_suffix = "_update_form"
    context_object_name = "todo_item"


class ToDoItemDeleteView(DeleteView):
    model = ToDoItem
    success_url = reverse_lazy("todo_list:list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

todo_manager/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <title>
    {% block title %}
      TODO App Index
    {% endblock %}
  </title>
</head>
<body>
<header>
  {% include "components/navbar.html" %}
</header>

<main class="container">
  {% block main %}
  {% endblock %}
</main>

<footer class="container m-4">
  {% block footer %}
    &copy; Django TODO App
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
          crossorigin="anonymous">
  </script>

</footer>
</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
  <ul>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'todo_list:index' %}">Todo List</a></li>
    <li><a href="#">About</a></li>
  </ul>
</nav>

todo_manager/templates/index.html
{% extends 'base.html' %}

{% block main %}
  <h1>Welcome to my TODO app!</h1>
  <h2>Work in progress</h2>
  <h3>It is {% now "jS F Y H:i" %}</h3>
  <p>{% lorem 3 p random %}</p>
{% endblock %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}


{% block footer %}
	{{ block.super }}
  <br>
  ToDo List
{% endblock %}

todo_manager/todo_list/templates/todo_list/components/todo_items_list.html
<ul class="list-group">
  {% for item in todo_items %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div>
        <a href="{% url 'todo_list:detail' pk=item.pk %}">
          {{ item.title }}
        </a>
        {% if item.done %}
          ✅
        {% else %}
          ❌
        {% endif %}
      </div>

      <div>
        <a
          type="button"
          class="btn btn-warning btn-sm"
          href="{% url 'todo_list:update' pk=item.pk %}"
        >
          Edit
        </a>
        <a
          type="button"
          class="btn btn-danger btn-sm"
          href="{% url 'todo_list:delete' pk=item.pk %}"
        >
          Delete
        </a>
      </div>

    </li>
  {% endfor %}
</ul>

todo_manager/todo_list/templates/todo_list/done_items.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo List App
{% endblock %}

{% block main %}
  <h2>Done ToDos:</h2>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo List App
{% endblock %}

{% block main %}
  <h1>ToDo List App</h1>
  <ul>
    <li><a href="{% url 'todo_list:create' %}">Create a new ToDo Item</a></li>
    <li><a href="{% url 'todo_list:list' %}">All ToDo Items</a></li>
    <li><a href="{% url 'todo_list:done' %}">Done ToDo Items</a></li>
  </ul>
  <h2>ToDos:</h2>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_confirm_delete.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Delete ToDo #{{ object }}
{% endblock %}

{% block main %}
  <h2>Delete item - <strong>{{ object.title }}</strong>:</h2>
  <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
  </form>
  <a
    type="button"
    class="btn btn-outline-secondary my-4"
    href="{% url 'todo_list:list' %}"
  >
    Back to All ToDo Items
  </a>
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo # {{ todo_item.pk }}
{% endblock %}

{% block main %}
  <h3>Todo - <strong>{{ todo_item.title }}</strong>:</h3>
  <div>
    <div>Title: <strong>{{ todo_item.title }}</strong></div>
    <div>Done: <strong>{{ todo_item.done }}</strong></div>
    <div>Description: <strong>{{ todo_item.description }}</strong></div>
  </div>

  <a
    type="button"
    class="btn btn-warning btn-sm my-4"
    href="{% url 'todo_list:update' pk=todo_item.pk %}"
  >
    Update ToDo
  </a>
  <a
    type="button"
    class="btn btn-danger btn-sm my-4"
    href="{% url 'todo_list:delete' pk=todo_item.pk %}"
  >
    Delete ToDo
  </a>

{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_form.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Create new ToDo item
{% endblock %}

{% block main %}
  <h2>Create a new item:</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
  </form>
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_list.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo List App
{% endblock %}

{% block main %}
  <h2>All ToDos:</h2>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_update_form.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Update ToDo #{{ todo_item.id }}
{% endblock %}

{% block main %}
  <h2>Update item - <strong>{{ todo_item.title }}</strong>:</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
  </form>
  <a
    type="button"
    class="btn btn-outline-secondary my-4"
    href="{% url 'todo_list:list' %}"
  >
    Back to All ToDo Items
  </a>
{% endblock %}